spring:
  application:
    name: configServer
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ting-I186/config-repo
          skipSslValidation: true
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t
server:
  port: 8888
